Spring 8
entertainment-veks/hibernate pull request #10
Opened 2021-02-22 11:28 UTC by entertainment-veks

2021-02-22 12:54 UTC, NikolayFatkullin approved these changes

2021-02-22 12:54 UTC, NikolayFatkullin commented on src/main/java/hibernate/controller/InjectDataController.java
> +@RequestMapping("/inject-data")
Better to use "@Component" annotation here

2021-02-22 12:54 UTC, NikolayFatkullin commented on src/main/java/hibernate/service/impl/RoleServiceImpl.java
> +    private RoleDao roleDao;
it must be final

2021-02-22 14:37 UTC, RomanDubovskyi requested changes

2021-02-22 14:37 UTC, RomanDubovskyi commented on src/main/java/hibernate/controller/InjectDataController.java
> +public class InjectDataController {
```suggestion
public class DataInitializer {
```

2021-02-22 14:37 UTC, RomanDubovskyi commented on src/main/java/hibernate/controller/InjectDataController.java
> +        Role coolBobsRole = new Role();
```suggestion
        Role adminRole = new Role();
```

2021-02-22 14:37 UTC, RomanDubovskyi commented on src/main/java/hibernate/controller/InjectDataController.java
> +        Role commonAlicesRole = new Role();
```suggestion
        Role userRole = new Role();
```

2021-02-22 14:37 UTC, RomanDubovskyi commented on src/main/java/hibernate/model/User.java
> +    private List<Role> roles;
let's user Set instead since roles should be unique

2021-02-22 14:37 UTC, RomanDubovskyi commented on src/main/java/hibernate/security/CustomUserDetailsService.java
> +                new RuntimeException("Can't find user with email " + s));
throw UsernameNotFoundException instead of Runtime, that is more obvious behavior

2021-02-22 15:22 UTC, RomanDubovskyi commented
you didn't push any changes

2021-02-23 08:21 UTC, RomanDubovskyi approved these changes

2021-02-23 08:21 UTC, RomanDubovskyi commented on src/main/java/hibernate/security/CustomUserDetailsService.java
> +    public UserDetails loadUserByUsername(String s) throws UsernameNotFoundException {
```suggestion
    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
```

2021-02-23 08:21 UTC, RomanDubovskyi commented on src/main/java/hibernate/service/impl/RoleServiceImpl.java
> +    private final RoleDao roleDao;
why do you have final keyword here and don't have it in other services, keep your code consistent

2021-02-23 16:40 UTC, merged