init commit
entertainment-veks/hibernate pull request #5
Opened 2021-02-04 14:55 UTC by entertainment-veks

2021-02-04 16:26 UTC, Fedich09 approved these changes

2021-02-04 16:55 UTC, dmytro-hryhoruk requested changes

2021-02-04 16:55 UTC, dmytro-hryhoruk commented on src/main/java/hibernate/dao/impl/OrderDaoImpl.java
> +            Query<Order> query = session.createQuery("from Order o"
https://mateacademy.slack.com/archives/G01EHB8CWAE/p1612455330236200

2021-02-04 18:03 UTC, dmytro-hryhoruk requested changes

2021-02-04 18:03 UTC, dmytro-hryhoruk commented on src/main/java/hibernate/dao/impl/ShoppingCartDaoImpl.java
> +            return session.createQuery("SELECT DISTINCT s from ShoppingCart s "
?

2021-02-04 18:03 UTC, dmytro-hryhoruk commented on src/main/java/hibernate/dao/impl/ShoppingCartDaoImpl.java
> +            return session.createQuery("SELECT DISTINCT s from ShoppingCart s "
didn't get what you are doing here

2021-02-05 09:55 UTC, dmytro-hryhoruk approved these changes

2021-02-09 07:33 UTC, merged