spring-4
entertainment-veks/hibernate pull request #6
Opened 2021-02-12 10:54 UTC by entertainment-veks

refactored all services and daos
added AppConfig
removed old config filed
removed .lib forder

2021-02-12 16:06 UTC, vicire requested changes

2021-02-12 16:06 UTC, vicire commented on pom.xml
> +        </dependency>
Do you need this dependency?

2021-02-12 16:06 UTC, vicire commented on src/main/java/hibernate/Main.java
>          System.out.println(orderService.getOrdersHistory(bob));
You can remove your main

2021-02-12 16:40 UTC, vicire approved these changes

2021-02-15 07:51 UTC, boroda4436 approved these changes

2021-02-15 13:16 UTC, merged