added Security
entertainment-veks/hibernate pull request #9
Opened 2021-02-18 18:13 UTC by entertainment-veks

2021-02-18 19:09 UTC, NikolayFatkullin requested changes

2021-02-18 19:09 UTC, NikolayFatkullin commented on src/main/java/hibernate/model/dto/CinemaHallResponseDto.java
> +    @Size(min = 10)
You don't need to use validation on the Response Dto. Check all your's DTOs

2021-02-18 19:09 UTC, NikolayFatkullin commented on src/main/java/hibernate/model/dto/UserResponseDto.java
>      private String email;
You don't need to validate an email in the Response Dto

2021-02-18 19:09 UTC, NikolayFatkullin commented on src/main/java/hibernate/service/impl/UserServiceImpl.java
> +        this.securityConfig = securityConfig;
You need to use the Password Encoder object here

2021-02-18 20:04 UTC, NikolayFatkullin approved these changes

2021-02-19 09:33 UTC, boroda4436 approved these changes

2021-02-19 09:44 UTC, merged